set nocompatible
set nobackup
set backspace=indent,eol,start
set number
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set t_Co=256
let g:base16_shell_path='/home/s9n/.config/base16-shell/scripts/'
colorscheme base16-oceanicnext
let base16colorspace=256
syntax on
